import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Satisfy } from 'next/font/google';
import SmoothScroll from './components/SmoothScroll'
import "./globals.css";

const satisfy = Satisfy({
  subsets: ['latin'],
  weight: '400',
  variable: "--font-satisfy"
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
  variable: "--font-poppins"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${satisfy.variable}`}>
        <SmoothScroll />
        {children}
      </body>
    </html>
  );
}
